FROM python:3.9-slim

# Install Ansible and dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends sshpass && \
    pip install --no-cache-dir ansible boto3 botocore && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /workspace

# Set entrypoint
ENTRYPOINT ["ansible-playbook"]
